### ISSUE TITLE
Tapir fails on 1.11

### ISSUE THREAD

**Issue by gdalle** [compintell/Mooncake.jl#180]
Heads up, I tried running the DI test suite on Julia 1.11-beta2, and Tapir failed

https://github.com/gdalle/DifferentiationInterface.jl/actions/runs/9378628896/job/25822187188?pr=302

**Comment by willtebbutt** [comment]
Yup -- I think this is probably the same issue as #118 . With the changes to arrays in 1.11, we're going to need to update stuff in Tapir.jl. I'm going to close that issue in favour of this one.

**Comment by willtebbutt** [comment]
This should be resolved by #288 . Please re-open this if v0.4.11 doesn't resolve this problem for you.

**Comment by gdalle** [comment]
Testing in https://github.com/gdalle/DifferentiationInterface.jl/pull/595

**Comment by willtebbutt** [comment]
ahhh crap. Sorry @gdalle I forgot to add in the DI integration tests in the last PR. I'll do so asap.

**Comment by willtebbutt** [comment]
I really must add those DI integration tests (although it looks like I didn't mess anything up this time haha).
