### ISSUE TITLE
Add a `TapirMode` that we can pass to `AutoTapir(mode=TapirMode(debug=true))`

### ISSUE THREAD

**Issue by yebai** [compintell/Mooncake.jl#215]
It will provide flexible control over how Tapir is run but avoid breaking changes to `ADTypes`. If `TapirMode` is changed in a breaking manner, we simply mark the corresponding Tapir release breaking so users won't be surprised. 

The name TapirMode can be anything we agree on.

**Comment by willtebbutt** [comment]
This is a good idea. We will need to do this prior to renaming / updating ADTypes.jl with the a new type.

**Comment by willtebbutt** [comment]
Resolved by #262
