### ISSUE TITLE
Remarks on documentation

### ISSUE THREAD

**Issue by gdalle** [compintell/Mooncake.jl#263]
First of all, first-class AD tutorial!!! I might legit point people towards it even if they don't use Mooncake.

A few suggestions that came to me while reading:

- Add an API reference somewhere. Docstrings in the middle of text are good but hard to find.
- It's not obvious what the difference is between a tangent and a `CoDual`
- The `rrule!!` in https://compintell.github.io/Mooncake.jl/dev/mathematical_interpretation/#The-Rule-Interface-(Round-2) is not up to date, I think the attributes are no longer called `x.tangent` and `x.primal`
- The hashtag comments in https://compintell.github.io/Mooncake.jl/dev/debug_mode/ don't behave the way you want, for instance they break the TOC

**Comment by willtebbutt** [comment]
Thanks for the feedback! Will look at addressing these.

**Comment by willtebbutt** [comment]
Thanks for reading through the docs and your feedback @gdalle -- it's much appreciated!
