### ISSUE TITLE
Add integration test for Bijectors

### ISSUE THREAD

**Issue by yebai** [compintell/Mooncake.jl#348]
We should perform similar tests in https://github.com/EnzymeAD/Enzyme.jl/pull/2037 for Mooncake. 

@mhauru, can you copy the tests over?

**Comment by willtebbutt** [comment]
Thanks Markus -- extra integration tests are always welcome!

**Comment by willtebbutt** [comment]
On this -- if you find failing tests, please don't worry about fixing them. We can just find a good way to mark them as failing, and open an issue which says "fix failing Bijectors.jl integration tests"
