### ISSUE TITLE
Using JuliaFormatter?

### ISSUE THREAD

**Issue by gdalle** [compintell/Mooncake.jl#388]
As I start to work on forward mode Mooncake, I realize my fingers go for `Ctrl + Shift + I` ("format document") regularly. But since the current code base is not formatted, this might affect the parts of files that my meaningful changes haven't touched.
Would you be open to setting up a JuliaFormatter style and test?

**Comment by willtebbutt** [comment]
Ah, yes, absolutely. What's the best way to sequence this? Should I take a look at doing this asap, or wait until we've got forwards mode stuff done?

**Comment by gdalle** [comment]
I can do it easily before we get to forward mode

**Comment by gdalle** [comment]
Just gotta tell me which style to go for

**Comment by willtebbutt** [comment]
Excellent. Blue is my preferred style!
